version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clientaudioflow
    ports:
      - 3001:80
  
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf