name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
        VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
        VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
        VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
        VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
        VITE_BACKEND_IP: ${{ secrets.VITE_BACKEND_IP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Create .env file
      #   run: |
      #     echo "VITE_API_KEY=${VITE_API_KEY}" >> .env
      #     echo "VITE_AUTH_DOMAIN=${VITE_AUTH_DOMAIN}" >> .env
      #     echo "VITE_PROJECT_ID=${VITE_PROJECT_ID}" >> .env
      #     echo "VITE_STORAGE_BUCKET=${VITE_STORAGE_BUCKET}" >> .env
      #     echo "VITE_MESSAGING_SENDER_ID=${VITE_MESSAGING_SENDER_ID}" >> .env
      #     echo "VITE_APP_ID=${VITE_APP_ID}" >> .env
      #     echo "VITE_BACKEND_IP=${VITE_BACKEND_IP}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clientaudioflow:latest
