name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:latest
        docker-compose down

    - name: login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pack Remote Build
      uses: dfreilich/pack-action@v2.1.1
      with:
        args: 'build clientaudioflow --builder heroku/builder:22 --publish'